# Generated by Django 2.1.1 on 2018-09-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='saddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='semail',
            new_name='email',
        ),
    ]
